version: '3'

networks:
  app-tier:
    driver: bridge

volumes:
  minio-data:
    driver: local
  db-data:
    driver: local
  es_data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: qaprotours
    depends_on:
      - postgres
      - minio
      - elastic-search
    env_file:
      - .env
    networks:
      - app-tier

  postgres:
    image: 'postgres:15.1-alpine'
    container_name: qaprotours-db
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-tier
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: qaprotours-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9000:9000'
      - '9090:9090'
    networks:
      - app-tier
    volumes:
      - minio-data:/minio

  nginx:
    image: nginx:latest
    container_name: qaprotours-nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - app
      - minio
    ports:
      - '80:80'
    networks:
      - app-tier

  elasticsearch:
    image: elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - app-tier

  kibana:
    image: kibana:8.7.1
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - app-tier
