spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/qaprotours?currentSchema=qaprotours}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/db.changelog.yaml
    enabled: true
    default-schema: qaprotours
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
  jwt:
    secret: c651749e8354adb09452a8ad14d4beadb7d57064d6cfb5c0e812bc30724458d187f43e58c22c30486303bbfc655391860952e92add87b5ce9e2ac7cdc612ad73=
    access: 5
    refresh: 336
springdoc:
  override-with-generic-response: false