spring:
  application:
    name: qaprotours
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DB}?currentSchema=${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:db/db.changelog.yaml
    enabled: true
    default-schema: ${POSTGRES_DB}
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DB}?currentSchema=${POSTGRES_DB}
    password: ${POSTGRES_PASSWORD}
    user: ${POSTGRES_USERNAME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  kafka:
    bootstrap-servers: ${KAFKA_HOST}

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      default:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
      imageService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

security:
  jwt:
    secret: c651749e8354adb09452a8ad14d4beadb7d57064d6cfb5c0e812bc30724458d187f43e58c22c30486303bbfc655391860952e92add87b5ce9e2ac7cdc612ad73=
    access: 30
    refresh: 336
    activation: 24
    reset: 24

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

mail:
  links:
    activation: http://localhost:8080/api/v1/auth/register/confirm?token=
    restore: http://localhost:8080/api/v1/auth/password/restore?token=

image:
  thumbnails:
    - 100
    - 400
  extensions:
    - jpg
    - jpeg
    - png
    - svg
    - webp

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

server:
  port: 8080