--liquibase formatted sql
--changeset ermakovich:1

create schema if not exists qaprotours;
set schema 'qaprotours';

CREATE TABLE IF NOT EXISTS addresses
(
    id           bigint generated by default as identity (START WITH 5),
    country      varchar(255) NOT NULL,
    city         varchar(255) NOT NULL,
    street       varchar(255) NOT NULL,
    house_number int          NOT NULL,
    constraint "address_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS hotels
(
    id           bigint generated by default as identity (START WITH 5),
    name         varchar(255) NOT NULL,
    coastline    int,
    stars_amount int,
    address_id   bigint       NOT NULL,
    constraint fk_address foreign key (address_id) references addresses (id) on delete cascade on update no action,
    constraint "hotel_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS tours
(
    id             bigint generated by default as identity (START WITH 5),
    name           varchar(255),
    description    varchar(1024),
    country        varchar(255),
    city           varchar(255),
    type           varchar(255),
    catering_type  varchar(255),
    hotel_id       bigint,
    arrival_time   timestamp without time zone,
    departure_time timestamp without time zone,
    place_amount   int,
    price          real,
    is_draft       boolean default true,
    rating         real,
    day_duration   int,
    latitude       double precision,
    longitude      double precision,
    constraint fk_hotel foreign key (hotel_id) references hotels (id) on delete cascade on update no action,
    constraint "tour_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS tour_image
(
    tour_id   bigint       NOT NULL,
    image_url varchar(255) NOT NULL,
    constraint fk_tour foreign key (tour_id) references tours (id) on delete cascade on update no action
);

CREATE TABLE IF NOT EXISTS tickets
(
    id            bigint generated by default as identity (START WITH 5),
    user_id       bigint,
    tour_id       bigint,
    order_time    timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status        varchar(255)                NOT NULL DEFAULT 'ORDERED',
    client_amount int                         NOT NULL,
    constraint fk_tour foreign key (tour_id) references tours (id) on delete cascade on update no action,
    constraint "ticket_pkey" PRIMARY KEY ("id")
);
