<html lang="en">
<head>
    <title>Reminder</title>
</head>
<body>
    <h1>Reminder</h1>
    <p>Hi, ${name}!</p>
    <p>Thank you for choosing our site. You have several tours in 2 days.</p>
    <p>
        ${ticket.tour.name} - ${ticket.tour.country} - ${ticket.tour.city} - <b>${ticket.tour.arrivalTime}</b>
    </p>
    <p>Please don't forget to take a passport and tickets.</p>
    <p>Best regards, <br> QaproTours</p>
</body>
</html>