<html lang="en">
<head>
    <title>Ticket canceled</title>
</head>
<body>
    <h1>Tour canceled</h1>
    <p>Hi, ${name}!</p>
    <p>You have not pay for tickets, so we cancel them.</p>
    <p>
        ${ticket.tour.name} - ${ticket.tour.country} - ${ticket.tour.city} - <b>${ticket.tour.arrivalTime}</b>
    </p>
    <p>Please don't forget to take a passport and tickets.</p>
    <p>Best regards, <br> QaproTours</p>
</body>
</html>