apiVersion: apps/v1
kind: Deployment
metadata:
  name: qaprotours
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qaprotours
  template:
    metadata:
      labels:
        app: qaprotours
    spec:
      serviceAccountName: qaprotours-serviceaccount
      containers:
        - name: qaprotours-app
          image: ilyalisov/qaprotours:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_PASSWORD
            - name: HOST
              value: postgres
            - name: POSTGRES_DB
              value: qaprotours
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: qaprotours-configmap
                  key: MINIO_BUCKET
            - name: MINIO_URL
              valueFrom:
                configMapKeyRef:
                  name: qaprotours-configmap
                  key: MINIO_URL
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_SECRET_KEY
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: qaprotours-configmap
                  key: KAFKA_HOST