apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qaprotours
spec:
  serviceName: qaprotours
  replicas: 1
  selector:
    matchLabels:
      app: qaprotours
  template:
    metadata:
      labels:
        app: qaprotours
    spec:
      serviceAccountName: qaprotours-serviceaccount
      containers:
        - name: qaprotours-app
          image: ilyalisov/qaprotours:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_PASSWORD
            - name: HOST
              value: postgres
            - name: POSTGRES_DB
              value: qaprotours
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: qaprotours-configmap
                  key: MINIO_BUCKET
            - name: MINIO_URL
              valueFrom:
                configMapKeyRef:
                  name: qaprotours-configmap
                  key: MINIO_URL
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_SECRET_KEY
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: qaprotours-configmap
                  key: KAFKA_HOST
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: qaprotours-configmap
                  key: USER_SERVICE_URL
            - name: ELASTIC_SEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: qaprotours-configmap
                  key: ELASTIC_SEARCH_HOST
            - name: ELASTIC_SEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: qaprotours-configmap
                  key: ELASTIC_SEARCH_PORT
          volumeMounts:
            - name: my-service-account-token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
      volumes:
        - name: my-service-account-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3600
        - name: logs-data
          hostPath:
            path: /logs
  volumeClaimTemplates:
    - metadata:
        name: logs-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi