apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner-api-cluster-role-binding
  namespace: actions-runner-system
subjects:
  - kind: ServiceAccount
    name: github-runner-api-sa
    namespace: actions-runner-system
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io