apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-stateful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: qaprotours-zookeeper
          image: confluentinc/cp-zookeeper:6.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-configmap
                  key: ZOOKEEPER_CLIENT_PORT
            - name: ZOOKEEPER_TICK_TIME
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-configmap
                  key: ZOOKEEPER_TICK_TIME
            - name: ZOOKEEPER_SYNC_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-configmap
                  key: ZOOKEEPER_SYNC_LIMIT