name: Code coverage

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate report
        run: mvn verify
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3