coverage:
  status:
    patch: off
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        flags:
          - unit
        paths:
          - "src/main/java/com/solvd/qaprotours/service/impl"
        # advanced settings
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false